import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "next-themes";
import LottieClient from "@/components/lottiePlayer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ali Raza Mern developer",
  description: "Generated by create next",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
      <body  className={inter.className}> <ThemeProvider attribute="class" defaultTheme="system">{children}</ThemeProvider>
        <LottieClient/>
      </body>
    </html>
  );
}
