import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import LottieClient from "@/components/lottiePlayer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ali Raza Mern developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
        <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>    
      </head> */}
      <body  className={inter.className}> <ThemeProvider attribute="class" defaultTheme="system">{children}</ThemeProvider>
        <LottieClient/>
      </body>
    </html>
  );
}
